
name: allinone
description: Um aplicativo Flutter interativo com funcionalidades dinâmicas.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/head.png
    - assets/images/tail.png
    - assets/images/coin.png